image: "ruby:2.4"

cache:
  paths:
    - vendor/ruby

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - gem install bundler  --no-ri --no-rdoc
  - bundle install

test:
  script:
  - ruby tests/gitlab_mirror_pull_test.rb

deploy:
  type: deploy
  environment: production
  script:
  - echo $GEM_API_PART1 > ~/.gem/credentials && echo $GEM_API_PART2 >> ~/.gem/credentials && chmod 0600 ~/.gem/credentials
  - gem build gitlab-mirror-pull.gemspec
  - export GEMVERSION=`grep -oP  -m 1 "s.version(.*)=(.*)'(.*)'" ./gitlab-mirror-pull.gemspec | awk -F "'" '{print $2}'`
  - echo $GEMVERSION
  - gem push gitlab-mirror-pull-$GEMVERSION.gem
