# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ruby -v                               # Print out ruby version for debugging
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install  # Install dependencies into ./vendor/ruby

test:
  script:
  - ruby tests/gitlab_mirror_pull_test.rb

deploy:
  type: deploy
  environment: production
  script:
  - echo $GEM_API_PART1 > ~/.gem/credentials && echo $GEM_API_PART2 >> ~/.gem/credentials && chmod 0600 ~/.gem/credentials
  - gem build gitlab-mirror-pull.gemspec
  - export GEMVERSION=`grep -oP  -m 1 "s.version(.*)=(.*)'(.*)'" ./gitlab-mirror-pull.gemspec | awk -F "'" '{print $2}'`
  - echo $GEMVERSION
  - gem push gitlab-mirror-pull-$GEMVERSION.gem
