git:
  path: "/usr/bin/git"
  repos: "/var/opt/gitlab/git-data/repositories" # Default path of gitlab omnibus installation
ignore:
  - "group-name/project-name" # Ignore single repo
  - "group-name" # Ignore entire group
provider: # provider equals to "remote" set in your repository
  - "github"
  - "gitlab"
api:
  url: "https://gitlab.example.org/"
  token: "XXXXXXXXXXX"
pipeline:
  enabled: false
  trigger:
    repo1:
      repo: "user_group/repo_1" # Run pipeline for single project
      branch: "master" # Branch to trigger pipeline
    repo2:
      repo: "user_group/repo_1" # Run pipeline for single project
      branch: "user_group" # Branch to trigger pipeline
server:
  port: 8088
  bind: "localhost"
mail:
  sender: "example@gmail.com"
  receiver: "example@gmail.com"
  send_on_error: false
  send_report: false
