git:
  path: "/usr/bin/git"
  repos: "/var/opt/gitlab/git-data/repositories" # Default path of gitlab omnibus installation
ignore:
  - "group-name/project-name" # Ignore single repo
  - "group-name" # Ignore entire group
provider: # provider equals to "remote" set in your repository
  - "github"
  - "gitlab"
api:
  url: "https://gitlab.example.org/"
  token: "XXXXXXXXXXX"
pipeline_trigger:
  - "user_group/repo_2" # Run pipeline for single project
server:
  port: 8088
  bind: "localhost"
mail:
  sender: "example@gmail.com"
  receiver: "example@gmail.com"
  send_on_error: false
  send_report: false
